In [1]:
import numpy as np

## Numpy Array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [8]:
matrixListesi2 = [[2,5,8] ,[22,8889,45]]


In [9]:
np.array(matrixListesi2)

array([[   2,    5,    8],
       [  22, 8889,   45]])

## Arange

In [10]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(20,100,6)

array([20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80, 86, 92, 98])

# Zeros

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((9,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## LinSpace

In [18]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

## Eye

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

In [20]:
np.random.randn(4)

array([ 0.35409241, -1.46482037, -0.61953494,  1.22650853])

In [21]:
np.random.randn(8,8)

array([[ 0.38945725,  1.29459105, -0.58752342,  0.87049833, -0.46994118,
        -0.31010065, -0.84541946, -0.08281664],
       [-1.14167733, -1.92978367,  0.23240532,  0.08421425, -1.41839666,
         0.62228621,  0.35258542, -1.07251659],
       [ 1.10429903,  0.1081969 ,  0.49248125, -0.27883409, -0.99850924,
        -0.20299828,  1.77774425,  0.50639901],
       [ 1.45033394,  0.19682524, -1.06665766,  0.05912627, -0.92475094,
         1.14361402,  1.42405261,  0.71552083],
       [-0.52118121, -0.13099749, -1.70705379,  0.37561423,  1.23397974,
         0.63741651, -2.28210962,  0.61993412],
       [-0.32054517, -0.11097216, -0.87363658,  1.05701282, -1.33906306,
         1.14798223, -1.92900299, -0.50442548],
       [ 0.51276359, -0.49466136,  0.41151108,  0.04164942, -1.13767863,
         1.31955237, -1.25750889, -0.18427155],
       [-0.65059573,  0.74031979, -0.51407905,  0.5428259 , -1.3239468 ,
         0.72875435,  0.33056182, -0.25988663]])

In [22]:
np.random.randint(1,10)

7

In [23]:
np.random.randint(1,300,5)

array([ 71, 278,  47,  56, 212], dtype=int32)

In [24]:
benimNumpyDizim = np.arange(30)

In [25]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
benimRandomDizim = np.random.randint(0,100,20)

In [27]:
benimRandomDizim

array([ 5, 74, 44,  6, 79, 70,  5, 32, 57, 55, 33,  1, 75, 95, 57, 28, 76,
       83, 35, 28], dtype=int32)

## Numpy Dizi Methodları

In [28]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
benimNumpyDizim.max()

np.int64(29)

In [30]:
benimRandomDizim.max()

np.int32(95)

In [31]:
benimNumpyDizim.min()

np.int64(0)

In [32]:
benimRandomDizim.argmax()

np.int64(13)

In [33]:
benimRandomDizim.argmin()

np.int64(11)

In [34]:
reshapeDizim = benimNumpyDizim.reshape(6,5)

In [35]:
# (5,6)