In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [7]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8] = -5

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingDizisi = baskaDizi[4:9]

In [14]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [15]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
slicingDizisi[:] = 700

In [17]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [18]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [19]:
ornekDizi = np.arange(0,24)

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasi = ornekDizi.copy()

In [22]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [24]:
ornekDiziKopyasiSlicing[:] = 800

In [25]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [26]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [28]:
benimListem = [[10,20,30],[20,30,40],[30,40,50]]

In [29]:
benimMatrixDizim = np.array(benimListem)

In [30]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [31]:
benimMatrixDizim[2]

array([30, 40, 50])

In [32]:
benimMatrixDizim[1][2]

40

In [33]:
benimMatrixDizim[1,2]

40

In [43]:
benimMatrixDizim[0:,2] # : ifadesi bulunan konum ve sonrasını alıyoruz demektir.

array([30, 40, 50])

In [35]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [36]:
yeniMatrix = np.array(yeniListe)

In [37]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
yeniMatrix[[2,2,1]]

array([[10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

## Operasyonlar

In [46]:
yeniBirDizi = np.random.randint(1,100,20)

In [47]:
yeniBirDizi

array([34, 52,  5, 53, 24,  8, 74, 58, 15, 84, 85,  3, 46, 59, 33, 69, 27,
       29, 52, 31])

In [48]:
yeniBirDizi > 24

array([ True,  True, False,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [49]:
sonucDizisi = yeniBirDizi > 24

In [50]:
sonucDizisi

array([ True,  True, False,  True, False, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
yeniBirDizi[sonucDizisi]

array([34, 52, 53, 74, 58, 84, 85, 46, 59, 33, 69, 27, 29, 52, 31])

In [52]:
yeniBirDizi[yeniBirDizi > 24]

array([34, 52, 53, 74, 58, 84, 85, 46, 59, 33, 69, 27, 29, 52, 31])

In [53]:
sonDizi = np.arange(0,24)

In [54]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [56]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [58]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [59]:
sonDizi / sonDizi

C:\Users\aliem\AppData\Local\Temp\ipykernel_24284\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [60]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [61]:
np.max(sonDizi)

23

In [62]:
np.min(sonDizi)

0